name: jupyter-videochat-docs

channels:
  - conda-forge
  - conda-forge/label/jupyterlab_rc

dependencies:
  # run
  - escapism
  - python >=3.6,<3.10
  # build
  - nodejs >=14,<15
  - pip
  - twine
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-jsonschema

  # lite
  - jupyterlab >=3.1.0rc2,<4
  - pip:
      - jupyterlite ==0.1.0a6
      - retrolab >=0.3.0rc1
