name: jupyter-videochat-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  # run
  - escapism
  - python >=3.7,<3.10
  # build
  - nodejs >=14,!=15,<17
  - pip
  - twine
  # docs
  - ipywidgets
  - myst-nb
  - pydata-sphinx-theme
  - pytest-check-links
  - sphinx
  - sphinx-jsonschema

  # lite
  - jupyterlab >=3.3.0,<4
  - retrolab >=0.3.20
  - pip:
      - jupyterlite ==0.1.0b4
