#!/usr/bin/env bash
set -eux

jlpm bootstrap

python -m pip install -e . --ignore-installed --no-deps -vv

jupyter labextension disable jupyter-offlinenotebook || echo "not enabled"
jupyter labextension uninstall --no-build jupyter-offlinenotebook || echo "not installed"

jupyter labextension develop --overwrite .
jupyter serverextension enable --sys-prefix --py jupyter_videochat

jupyter serverextension list
jupyter labextension list
